import("//sdkpath.gni")


static_library("v8") {

  include_dirs = [

    "$ndkIncludePath",
    "$sdkPath/include/c++/7.2.0",
    "$sdkPath/include/c++/7.2.0/include",
    "$sdkPath/include/c++/7.2.0/x86_64-unknown-linux-gnu/",
    "$sdkPath2/usr/lib/x86_64-linux-gnu/glib-2.0/include",

    "$sdkPath/sysroot/usr/include",
    "$sdkPath/sysroot/usr/",
    "$sdkPath/sysroot/usr/include/linux",
    "$sdkPath2/usr/include/libdrm",

    "//",

    "$sdkPath2/usr/include/cairo",
    "$sdkPath2/usr/include/glib-2.0",
    "$sdkPath2/usr/include/gtk-3.0",
    "$sdkPath2/usr/include/gdk-pixbuf-2.0",
    "$sdkPath2/usr/include/atk-1.0",
    "$sdkPath2/usr/include/pango-1.0",

    "//linux",

    "//gen",
    "//third_party/abseil-cpp",
    "//v8",
    "//v8/include",

    "//third_party/icu/source/i18n",
    "//third_party/icu/source/common",
    "//third_party/openssl/openssl/include",

    "//gen/v8x64linux",
    "//gen/v8x64linux/include",


  ]

  cflags = [

    "-fms-extensions",
    "-frtti",
    "-D_GLIBCXX_USE_C99_MATH",
    "-D_CRT_SECURE_NO_WARNINGS",
    "-D_GLIBCXX_USE_CXX11_ABI=1",
    
    "-D_CRT_SECURE_NO_DEPRECATE",
    "-D_CRT_NONSTDC_NO_DEPRECATE",
    "-D_HAS_EXCEPTIONS=0",

    "-DNOMINMAX",
    "-DENABLE_DISASSEMBLER",
    "-DOBJECT_PRINT",
        
    "-DDYNAMIC_ANNOTATIONS_ENABLED=0",
    "-DV8_OS_LINUX",
    
    "-DV8_HAVE_TARGET_OS",
    "-DV8_TARGET_OS_LINUX",
    "-DBUILDING_V8_SHARED=1",
    "-DBUILDING_UV_SHARED=1",
    "-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64",
    "-DV8_INTL_SUPPORT",
    "-DV8_USE_EXTERNAL_STARTUP_DATA",
    "-DV8_ATOMIC_OBJECT_FIELD_WRITES",
    "-DV8_ENABLE_LAZY_SOURCE_POSITIONS",
    "-DV8_SHARED_RO_HEAP",
    "-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH",
    "-DV8_SHORT_BUILTIN_CALLS",
    "-DV8_ENABLE_SYSTEM_INSTRUMENTATION",
    # "-DV8_ENABLE_ETW_STACK_WALKING",
    "-DV8_ENABLE_WEBASSEMBLY",
    "-DV8_ALLOCATION_FOLDING",
    "-DV8_ALLOCATION_SITE_TRACKING",
    "-DV8_ADVANCED_BIGINT_ALGORITHMS",
    "-DV8_USE_ZLIB",
    # "-DV8_EXTERNAL_CODE_SPACE",
    # "-DV8_COMPRESS_POINTERS",
    # "-DV8_COMPRESS_POINTERS_IN_SHARED_CAGE",
    # "-DV8_31BIT_SMIS_ON_64BIT_ARCH",
    # "-DV8_DEPRECATION_WARNINGS",
    # "-DCPPGC_CAGED_HEAP",
    # "-DCPPGC_YOUNG_GENERATION",
    # "-DCPPGC_POINTER_COMPRESSION",
    
    # "-DENABLE_HANDLE_ZAPPING",
    "-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_SHARED",
    "-DUCONFIG_NO_SERVICE=1",
    "-DU_ENABLE_DYLOAD=0",
    "-DU_STATIC_IMPLEMENTATION=1",
    "-DU_HAVE_STD_STRING=1",
    "-DUCONFIG_NO_BREAK_ITERATION=0",

    "-fPIC", 
    "-fno-exceptions", 
    "-fvisibility=hidden", 
    "--target=x86_64-linux-guneabi", 
    "-DUSE_EGL", 
    "-DSK_GL", 
    "-DSK_SUPPORT_GPU=1", 
    "-DSK_GRAPHITE_ENABLED", 
    "-DSK_SUPPORT_LEGACY_SLUG_CONVERT", 
    "-DSK_B32_SHIFT=16", 
    "-DSK_G32_SHIFT=8", 
    "-DSK_R32_SHIFT=0", 
    "-DSK_A32_SHIFT=24", 
    "-DOS_LINUX=1", 
    "-DENABLE_MB_MEDIA=1", 
    "-DV8_HOST_ARCH_X64", 
    "-DV8_TARGET_ARCH_X64", 
    "-D__POINT_SIZE__=8", 
    "-D__USE_OPENGL__", 
    "-DV8_ENABLE_MAGLEV", 
    "-mno-avx", 
    "-DV8_EXTERNAL_CODE_SPACE",
    "-DV8_DEPRECATION_WARNINGS", 
    "-DV8_COMPRESS_POINTERS", 
    "-DV8_COMPRESS_POINTERS_IN_SHARED_CAGE", 
    "-DV8_31BIT_SMIS_ON_64BIT_ARCH", 
    "-DCPPGC_CAGED_HEAP", 
    "-DCPPGC_YOUNG_GENERATION", 
    "-DCPPGC_POINTER_COMPRESSION",  
  ]

  sources = [

    "//v8/src/api/api-natives.cc",
    "//v8/src/api/api.cc",
    "//v8/src/api/api-arguments.cc",
    "//v8/src/asmjs/asm-js.cc",
    "//v8/src/asmjs/asm-parser.cc",
    "//v8/src/asmjs/asm-scanner.cc",
    "//v8/src/asmjs/asm-types.cc",
    "//v8/src/ast/ast-function-literal-id-reindexer.cc",
    "//v8/src/ast/ast-value-factory.cc",
    "//v8/src/ast/modules.cc",
    "//v8/src/ast/prettyprinter.cc",
    "//v8/src/ast/scopes.cc",
    "//v8/src/ast/source-range-ast-visitor.cc",
    "//v8/src/ast/variables.cc",
    "//v8/src/ast/ast.cc",
    "//v8/src/base/debug/stack_trace_posix.cc",
    "//v8/src/base/debug/stack_trace.cc",
    "//v8/src/base/numbers/bignum.cc",
    "//v8/src/base/numbers/bignum-dtoa.cc",
    "//v8/src/base/numbers/cached-powers.cc",
    "//v8/src/base/numbers/diy-fp.cc",
    "//v8/src/base/numbers/dtoa.cc",
    "//v8/src/base/numbers/fast-dtoa.cc",
    "//v8/src/base/numbers/fixed-dtoa.cc",
    "//v8/src/base/numbers/strtod.cc",
    "//v8/src/base/platform/time.cc",
    "//v8/src/base/platform/condition-variable.cc",
    "//v8/src/base/platform/memory-protection-key.cc",
    "//v8/src/base/platform/mutex.cc",
    "//v8/src/base/platform/platform-posix.cc",
    "//v8/src/base/platform/platform-linux.cc",
    "//v8/src/base/platform/platform-posix-time.cc",
    "//v8/src/base/platform/semaphore.cc",
    "//v8/src/base/sanitizer/lsan-virtual-address-space.cc",
    "//v8/src/base/sanitizer/lsan-page-allocator.cc",
    "//v8/src/base/utils/random-number-generator.cc",
    "//v8/src/base/ieee754.cc",
    "//v8/src/base/logging.cc",
    "//v8/src/base/once.cc",
    "//v8/src/base/page-allocator.cc",
    "//v8/src/base/region-allocator.cc",
    "//v8/src/base/strings.cc",
    "//v8/src/base/sys-info.cc",
    "//v8/src/base/virtual-address-space.cc",
    "//v8/src/base/virtual-address-space-page-allocator.cc",
    "//v8/src/base/vlq-base64.cc",
    "//v8/src/base/bits.cc",
    "//v8/src/base/bounded-page-allocator.cc",
    "//v8/src/base/cpu.cc",
    "//v8/src/base/division-by-constant.cc",
    "//v8/src/base/emulated-virtual-address-subspace.cc",
    "//v8/src/base/file-utils.cc",
    "//v8/src/baseline/baseline-compiler.cc",
    "//v8/src/baseline/bytecode-offset-iterator.cc",
    "//v8/src/baseline/baseline.cc",
    "//v8/src/baseline/baseline-batch-compiler.cc",
    "//v8/src/bigint/mul-toom.cc",
    "//v8/src/bigint/tostring.cc",
    "//v8/src/bigint/vector-arithmetic.cc",
    "//v8/src/bigint/bigint-internal.cc",
    "//v8/src/bigint/bitwise.cc",
    "//v8/src/bigint/div-barrett.cc",
    "//v8/src/bigint/div-burnikel.cc",
    "//v8/src/bigint/div-helpers.cc",
    "//v8/src/bigint/div-schoolbook.cc",
    "//v8/src/bigint/fromstring.cc",
    "//v8/src/bigint/mul-fft.cc",
    "//v8/src/bigint/mul-karatsuba.cc",
    "//v8/src/bigint/mul-schoolbook.cc",
    "//v8/src/builtins/x64/builtins-x64.cc",
    "//v8/src/builtins/arm64/builtins-arm64.cc",
    "//v8/src/builtins/arm/builtins-arm.cc",
    "//v8/src/builtins/accessors.cc",
    "//v8/src/builtins/builtins-web-snapshots.cc",
    "//v8/src/builtins/builtins.cc",
    "//v8/src/builtins/builtins-api.cc",
    "//v8/src/builtins/builtins-array.cc",
    "//v8/src/builtins/builtins-arraybuffer.cc",
    "//v8/src/builtins/builtins-array-gen.cc",
    "//v8/src/builtins/builtins-async-function-gen.cc",
    "//v8/src/builtins/builtins-async-gen.cc",
    "//v8/src/builtins/builtins-async-generator-gen.cc",
    "//v8/src/builtins/builtins-async-iterator-gen.cc",
    "//v8/src/builtins/builtins-async-module.cc",
    "//v8/src/builtins/builtins-atomics-synchronization.cc",
    "//v8/src/builtins/builtins-bigint.cc",
    "//v8/src/builtins/builtins-bigint-gen.cc",
    "//v8/src/builtins/builtins-call-gen.cc",
    "//v8/src/builtins/builtins-callsite.cc",
    "//v8/src/builtins/builtins-collections.cc",
    "//v8/src/builtins/builtins-collections-gen.cc",
    "//v8/src/builtins/builtins-console.cc",
    "//v8/src/builtins/builtins-constructor-gen.cc",
    "//v8/src/builtins/builtins-conversion-gen.cc",
    "//v8/src/builtins/builtins-dataview.cc",
    "//v8/src/builtins/builtins-date.cc",
    "//v8/src/builtins/builtins-date-gen.cc",
    "//v8/src/builtins/builtins-error.cc",
    "//v8/src/builtins/builtins-function.cc",
    "//v8/src/builtins/builtins-generator-gen.cc",
    "//v8/src/builtins/builtins-global.cc",
    "//v8/src/builtins/builtins-global-gen.cc",
    "//v8/src/builtins/builtins-handler-gen.cc",
    "//v8/src/builtins/builtins-ic-gen.cc",
    "//v8/src/builtins/builtins-internal.cc",
    "//v8/src/builtins/builtins-internal-gen.cc",
    "//v8/src/builtins/builtins-interpreter-gen.cc",
    "//v8/src/builtins/builtins-iterator-gen.cc",
    "//v8/src/builtins/builtins-json.cc",
    "//v8/src/builtins/builtins-lazy-gen.cc",
    "//v8/src/builtins/builtins-microtask-queue-gen.cc",
    "//v8/src/builtins/builtins-number.cc",
    "//v8/src/builtins/builtins-number-gen.cc",
    "//v8/src/builtins/builtins-object.cc",
    "//v8/src/builtins/builtins-object-gen.cc",
    "//v8/src/builtins/builtins-promise-gen.cc",
    "//v8/src/builtins/builtins-proxy-gen.cc",
    "//v8/src/builtins/builtins-reflect.cc",
    "//v8/src/builtins/builtins-regexp.cc",
    "//v8/src/builtins/builtins-regexp-gen.cc",
    "//v8/src/builtins/builtins-shadow-realm.cc",
    "//v8/src/builtins/builtins-shadow-realm-gen.cc",
    "//v8/src/builtins/builtins-shared-array.cc",
    "//v8/src/builtins/builtins-sharedarraybuffer.cc",
    "//v8/src/builtins/builtins-sharedarraybuffer-gen.cc",
    "//v8/src/builtins/builtins-string.cc",
    "//v8/src/builtins/builtins-string-gen.cc",
    "//v8/src/builtins/builtins-struct.cc",
    "//v8/src/builtins/builtins-symbol.cc",
    "//v8/src/builtins/builtins-temporal.cc",
    "//v8/src/builtins/builtins-temporal-gen.cc",
    "//v8/src/builtins/builtins-trace.cc",
    "//v8/src/builtins/builtins-typed-array.cc",
    "//v8/src/builtins/builtins-typed-array-gen.cc",
    "//v8/src/builtins/builtins-wasm-gen.cc",
    "//v8/src/builtins/builtins-weak-refs.cc",
    "//v8/src/builtins/constants-table-builder.cc",
    "//v8/src/builtins/generate-bytecodes-builtins-list.cc",
    "//v8/src/builtins/growable-fixed-array-gen.cc",
    "//v8/src/builtins/profile-data-reader.cc",
    "//v8/src/builtins/setup-builtins-internal.cc",
    "//v8/src/codegen/x64/assembler-x64.cc",
    "//v8/src/codegen/x64/macro-assembler-x64.cc",
    "//v8/src/codegen/x64/cpu-x64.cc",
    "//v8/src/codegen/arm64/assembler-arm64.cc",
    "//v8/src/codegen/arm64/cpu-arm64.cc",
    "//v8/src/codegen/arm64/decoder-arm64.cc",
    "//v8/src/codegen/arm64/instructions-arm64.cc",
    "//v8/src/codegen/arm64/instructions-arm64-constants.cc",
    "//v8/src/codegen/arm64/macro-assembler-arm64.cc",
    "//v8/src/codegen/arm64/register-arm64.cc",
    "//v8/src/codegen/arm64/utils-arm64.cc",
    "//v8/src/codegen/arm/cpu-arm.cc",
    "//v8/src/codegen/arm/assembler-arm.cc",
    "//v8/src/codegen/arm/constants-arm.cc",
    "//v8/src/codegen/arm/macro-assembler-arm.cc",
    "//v8/src/codegen/external-reference.cc",
    "//v8/src/codegen/external-reference-encoder.cc",
    "//v8/src/codegen/external-reference-table.cc",
    "//v8/src/codegen/flush-instruction-cache.cc",
    "//v8/src/codegen/handler-table.cc",
    "//v8/src/codegen/interface-descriptors.cc",
    "//v8/src/codegen/machine-type.cc",
    "//v8/src/codegen/maglev-safepoint-table.cc",
    "//v8/src/codegen/optimized-compilation-info.cc",
    "//v8/src/codegen/pending-optimization-table.cc",
    "//v8/src/codegen/register-configuration.cc",
    "//v8/src/codegen/reloc-info.cc",
    "//v8/src/codegen/safepoint-table.cc",
    "//v8/src/codegen/source-position.cc",
    "//v8/src/codegen/source-position-table.cc",
    "//v8/src/codegen/string-constants.cc",
    "//v8/src/codegen/tick-counter.cc",
    "//v8/src/codegen/tnode.cc",
    "//v8/src/codegen/turbo-assembler.cc",
    "//v8/src/codegen/unoptimized-compilation-info.cc",
    "//v8/src/codegen/aligned-slot-allocator.cc",
    "//v8/src/codegen/assembler.cc",
    "//v8/src/codegen/bailout-reason.cc",
    "//v8/src/codegen/code-comments.cc",
    "//v8/src/codegen/code-desc.cc",
    "//v8/src/codegen/code-factory.cc",
    "//v8/src/codegen/code-reference.cc",
    "//v8/src/codegen/code-stub-assembler.cc",
    "//v8/src/codegen/compilation-cache.cc",
    "//v8/src/codegen/compiler.cc",
    "//v8/src/codegen/constant-pool.cc",
    "//v8/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.cc",
    "//v8/src/common/assert-scope.cc",
    "//v8/src/common/code-memory-access.cc",
    "//v8/src/compiler/access-builder.cc",
    "//v8/src/compiler/access-info.cc",
    "//v8/src/compiler/add-type-assertions-reducer.cc",
    "//v8/src/compiler/all-nodes.cc",
    "//v8/src/compiler/basic-block-instrumentor.cc",
    "//v8/src/compiler/branch-condition-duplicator.cc",
    "//v8/src/compiler/branch-elimination.cc",
    "//v8/src/compiler/bytecode-analysis.cc",
    "//v8/src/compiler/bytecode-graph-builder.cc",
    "//v8/src/compiler/bytecode-liveness-map.cc",
    "//v8/src/compiler/checkpoint-elimination.cc",
    "//v8/src/compiler/c-linkage.cc",
    "//v8/src/compiler/code-assembler.cc",
    "//v8/src/compiler/common-node-cache.cc",
    "//v8/src/compiler/common-operator.cc",
    "//v8/src/compiler/common-operator-reducer.cc",
    "//v8/src/compiler/compilation-dependencies.cc",
    "//v8/src/compiler/compiler-source-position-table.cc",
    "//v8/src/compiler/constant-folding-reducer.cc",
    "//v8/src/compiler/control-equivalence.cc",
    "//v8/src/compiler/control-flow-optimizer.cc",
    "//v8/src/compiler/csa-load-elimination.cc",
    "//v8/src/compiler/dead-code-elimination.cc",
    "//v8/src/compiler/decompression-optimizer.cc",
    "//v8/src/compiler/effect-control-linearizer.cc",
    "//v8/src/compiler/escape-analysis.cc",
    "//v8/src/compiler/escape-analysis-reducer.cc",
    "//v8/src/compiler/fast-api-calls.cc",
    "//v8/src/compiler/feedback-source.cc",
    "//v8/src/compiler/frame.cc",
    "//v8/src/compiler/frame-states.cc",
    "//v8/src/compiler/graph.cc",
    "//v8/src/compiler/graph-assembler.cc",
    "//v8/src/compiler/graph-reducer.cc",
    "//v8/src/compiler/graph-trimmer.cc",
    "//v8/src/compiler/graph-visualizer.cc",
    "//v8/src/compiler/heap-refs.cc",
    "//v8/src/compiler/int64-lowering.cc",
    "//v8/src/compiler/js-call-reducer.cc",
    "//v8/src/compiler/js-context-specialization.cc",
    "//v8/src/compiler/js-create-lowering.cc",
    "//v8/src/compiler/js-generic-lowering.cc",
    "//v8/src/compiler/js-graph.cc",
    "//v8/src/compiler/js-heap-broker.cc",
    "//v8/src/compiler/js-inlining.cc",
    "//v8/src/compiler/js-inlining-heuristic.cc",
    "//v8/src/compiler/js-intrinsic-lowering.cc",
    "//v8/src/compiler/js-native-context-specialization.cc",
    "//v8/src/compiler/js-operator.cc",
    "//v8/src/compiler/js-typed-lowering.cc",
    "//v8/src/compiler/js-type-hint-lowering.cc",
    "//v8/src/compiler/late-escape-analysis.cc",
    "//v8/src/compiler/linear-scheduler.cc",
    "//v8/src/compiler/linkage.cc",
    "//v8/src/compiler/load-elimination.cc",
    "//v8/src/compiler/loop-analysis.cc",
    "//v8/src/compiler/loop-peeling.cc",
    "//v8/src/compiler/loop-unrolling.cc",
    "//v8/src/compiler/loop-variable-optimizer.cc",
    "//v8/src/compiler/machine-graph.cc",
    "//v8/src/compiler/machine-graph-verifier.cc",
    "//v8/src/compiler/machine-operator.cc",
    "//v8/src/compiler/machine-operator-reducer.cc",
    "//v8/src/compiler/map-inference.cc",
    "//v8/src/compiler/memory-lowering.cc",
    "//v8/src/compiler/memory-optimizer.cc",
    "//v8/src/compiler/node.cc",
    "//v8/src/compiler/node-marker.cc",
    "//v8/src/compiler/node-matchers.cc",
    "//v8/src/compiler/node-observer.cc",
    "//v8/src/compiler/node-origin-table.cc",
    "//v8/src/compiler/node-properties.cc",
    "//v8/src/compiler/opcodes.cc",
    "//v8/src/compiler/operation-typer.cc",
    "//v8/src/compiler/operator.cc",
    "//v8/src/compiler/operator-properties.cc",
    "//v8/src/compiler/osr.cc",
    "//v8/src/compiler/pipeline.cc",
    "//v8/src/compiler/pipeline-statistics.cc",
    "//v8/src/compiler/property-access-builder.cc",
    "//v8/src/compiler/raw-machine-assembler.cc",
    "//v8/src/compiler/redundancy-elimination.cc",
    "//v8/src/compiler/refs-map.cc",
    "//v8/src/compiler/representation-change.cc",
    "//v8/src/compiler/schedule.cc",
    "//v8/src/compiler/scheduler.cc",
    "//v8/src/compiler/select-lowering.cc",
    "//v8/src/compiler/simplified-lowering.cc",
    "//v8/src/compiler/simplified-lowering-verifier.cc",
    "//v8/src/compiler/simplified-operator.cc",
    "//v8/src/compiler/simplified-operator-reducer.cc",
    "//v8/src/compiler/state-values-utils.cc",
    "//v8/src/compiler/store-store-elimination.cc",
    "//v8/src/compiler/type-cache.cc",
    "//v8/src/compiler/typed-optimization.cc",
    "//v8/src/compiler/type-narrowing-reducer.cc",
    "//v8/src/compiler/typer.cc",
    "//v8/src/compiler/types.cc",
    "//v8/src/compiler/value-numbering-reducer.cc",
    "//v8/src/compiler/verifier.cc",
    "//v8/src/compiler/wasm-compiler.cc",
    "//v8/src/compiler/wasm-escape-analysis.cc",
    "//v8/src/compiler/wasm-gc-lowering.cc",
    "//v8/src/compiler/wasm-gc-operator-reducer.cc",
    "//v8/src/compiler/wasm-graph-assembler.cc",
    "//v8/src/compiler/wasm-inlining.cc",
    "//v8/src/compiler/wasm-loop-peeling.cc",
    "//v8/src/compiler/wasm-typer.cc",
    "//v8/src/compiler/zone-stats.cc",
    "//v8/src/compiler/backend/x64/code-generator-x64.cc",
    "//v8/src/compiler/backend/x64/instruction-scheduler-x64.cc",
    "//v8/src/compiler/backend/x64/instruction-selector-x64.cc",
    "//v8/src/compiler/backend/x64/unwinding-info-writer-x64.cc",
    "//v8/src/compiler/backend/arm64/unwinding-info-writer-arm64.cc",
    "//v8/src/compiler/backend/arm64/instruction-selector-arm64.cc",
    "//v8/src/compiler/backend/arm64/instruction-scheduler-arm64.cc",
    "//v8/src/compiler/backend/arm64/code-generator-arm64.cc",
    "//v8/src/compiler/backend/arm/code-generator-arm.cc",
    "//v8/src/compiler/backend/arm/unwinding-info-writer-arm.cc",
    "//v8/src/compiler/backend/arm/instruction-selector-arm.cc",
    "//v8/src/compiler/backend/arm/instruction-scheduler-arm.cc",
    "//v8/src/compiler/backend/code-generator.cc",
    "//v8/src/compiler/backend/frame-elider.cc",
    "//v8/src/compiler/backend/gap-resolver.cc",
    "//v8/src/compiler/backend/instruction.cc",
    "//v8/src/compiler/backend/instruction-scheduler.cc",
    "//v8/src/compiler/backend/instruction-selector.cc",
    "//v8/src/compiler/backend/jump-threading.cc",
    "//v8/src/compiler/backend/mid-tier-register-allocator.cc",
    "//v8/src/compiler/backend/move-optimizer.cc",
    "//v8/src/compiler/backend/register-allocator.cc",
    "//v8/src/compiler/backend/register-allocator-verifier.cc",
    "//v8/src/compiler/backend/spill-placer.cc",
    "//v8/src/compiler-dispatcher/lazy-compile-dispatcher.cc",
    "//v8/src/compiler-dispatcher/optimizing-compile-dispatcher.cc",
    "//v8/src/date/date.cc",
    "//v8/src/date/dateparser.cc",
    "//v8/src/debug/debug.cc",
    "//v8/src/debug/debug-coverage.cc",
    "//v8/src/debug/debug-evaluate.cc",
    "//v8/src/debug/debug-frames.cc",
    "//v8/src/debug/debug-interface.cc",
    "//v8/src/debug/debug-property-iterator.cc",
    "//v8/src/debug/debug-scope-iterator.cc",
    "//v8/src/debug/debug-scopes.cc",
    "//v8/src/debug/debug-stack-trace-iterator.cc",
    "//v8/src/debug/debug-wasm-objects.cc",
    "//v8/src/debug/liveedit.cc",
    "//v8/src/debug/liveedit-diff.cc",
    "//v8/src/deoptimizer/x64/deoptimizer-x64.cc",
    "//v8/src/deoptimizer/arm64/deoptimizer-arm64.cc",
    "//v8/src/deoptimizer/arm/deoptimizer-arm.cc",
    "//v8/src/deoptimizer/deoptimized-frame-info.cc",
    "//v8/src/deoptimizer/deoptimizer.cc",
    "//v8/src/deoptimizer/deoptimizer-cfi-builtins.cc",
    "//v8/src/deoptimizer/deoptimize-reason.cc",
    "//v8/src/deoptimizer/materialized-object-store.cc",
    "//v8/src/deoptimizer/translated-state.cc",
    "//v8/src/deoptimizer/translation-array.cc",
    "//v8/src/diagnostics/x64/unwinder-x64.cc",
    "//v8/src/diagnostics/x64/eh-frame-x64.cc",
    "//v8/src/diagnostics/x64/disasm-x64.cc",
    "//v8/src/diagnostics/arm64/disasm-arm64.cc",
    "//v8/src/diagnostics/arm64/eh-frame-arm64.cc",
    "//v8/src/diagnostics/arm64/unwinder-arm64.cc",
    "//v8/src/diagnostics/arm/disasm-arm.cc",
    "//v8/src/diagnostics/arm/eh-frame-arm.cc",
    "//v8/src/diagnostics/arm/unwinder-arm.cc",
    "//v8/src/diagnostics/basic-block-profiler.cc",
    "//v8/src/diagnostics/compilation-statistics.cc",
    "//v8/src/diagnostics/disassembler.cc",
    "//v8/src/diagnostics/eh-frame.cc",
    "//v8/src/diagnostics/gdb-jit.cc",
    "//v8/src/diagnostics/objects-debug.cc",
    "//v8/src/diagnostics/objects-printer.cc",
    "//v8/src/diagnostics/perf-jit.cc",
    "//v8/src/diagnostics/unwinder.cc",
    "//v8/src/execution/x64/frame-constants-x64.cc",
    "//v8/src/execution/arm/frame-constants-arm.cc",
    "//v8/src/execution/arm64/frame-constants-arm64.cc",
    "//v8/src/execution/arm64/pointer-auth-arm64.cc",
    "//v8/src/execution/arm64/simulator-arm64.cc",
    "//v8/src/execution/arm64/simulator-logic-arm64.cc",
    "//v8/src/execution/arguments.cc",
    "//v8/src/execution/clobber-registers.cc",
    "//v8/src/execution/embedder-state.cc",
    "//v8/src/execution/encoded-c-signature.cc",
    "//v8/src/execution/execution.cc",
    "//v8/src/execution/frames.cc",
    "//v8/src/execution/futex-emulation.cc",
    "//v8/src/execution/interrupts-scope.cc",
    "//v8/src/execution/isolate.cc",
    "//v8/src/execution/local-isolate.cc",
    "//v8/src/execution/messages.cc",
    "//v8/src/execution/microtask-queue.cc",
    "//v8/src/execution/protectors.cc",
    "//v8/src/execution/simulator-base.cc",
    "//v8/src/execution/stack-guard.cc",
    "//v8/src/execution/thread-id.cc",
    "//v8/src/execution/thread-local-top.cc",
    "//v8/src/execution/tiering-manager.cc",
    "//v8/src/execution/v8threads.cc",
    "//v8/src/extensions/statistics-extension.cc",
    "//v8/src/extensions/trigger-failure-extension.cc",
    "//v8/src/extensions/cputracemark-extension.cc",
    "//v8/src/extensions/externalize-string-extension.cc",
    "//v8/src/extensions/gc-extension.cc",
    "//v8/src/extensions/ignition-statistics-extension.cc",
    "//v8/src/flags/flags.cc",
    "//v8/src/compiler/turboshaft/graph-builder.cc",
    "//v8/src/compiler/turboshaft/operations.cc",
    "//v8/src/compiler/turboshaft/optimization-phase.cc",
    "//v8/src/compiler/turboshaft/recreate-schedule.cc",
    "//v8/src/compiler/turboshaft/representations.cc",
    "//v8/src/compiler/turboshaft/simplify-tf-loops.cc",
    "//v8/src/compiler/turboshaft/utils.cc",
    "//v8/src/compiler/turboshaft/decompression-optimization.cc",
    "//v8/src/compiler/turboshaft/graph-visualizer-tur.cc",
    "//v8/src/compiler/turboshaft/graph-tur.cc",
    "//v8/src/builtins/builtins-intl.cc",
    "//v8/src/builtins/builtins-intl-gen.cc",
    "//v8/src/web-snapshot/web-snapshot.cc",
    "//v8/src/numbers/math-random.cc",
    "//v8/src/numbers/conversions.cc",
    "//v8/src/maglev/maglev.cc",
    "//v8/src/maglev/maglev-code-generator.cc",
    "//v8/src/maglev/maglev-compilation-info.cc",
    "//v8/src/maglev/maglev-compilation-unit.cc",
    "//v8/src/maglev/maglev-compiler.cc",
    "//v8/src/maglev/maglev-concurrent-dispatcher.cc",
    "//v8/src/maglev/maglev-graph-builder.cc",
    "//v8/src/maglev/maglev-graph-printer.cc",
    "//v8/src/maglev/maglev-interpreter-frame-state.cc",
    "//v8/src/maglev/maglev-ir.cc",
    "//v8/src/maglev/maglev-regalloc.cc",
    "//v8/src/objects/visitors.cc",
    "//v8/src/objects/backing-store.cc",
    "//v8/src/objects/bigint.cc",
    "//v8/src/objects/call-site-info.cc",
    "//v8/src/objects/code.cc",
    "//v8/src/objects/code-kind.cc",
    "//v8/src/objects/compilation-cache-table.cc",
    "//v8/src/objects/contexts.cc",
    "//v8/src/objects/debug-objects.cc",
    "//v8/src/objects/elements.cc",
    "//v8/src/objects/elements-kind.cc",
    "//v8/src/objects/embedder-data-array.cc",
    "//v8/src/objects/feedback-vector.cc",
    "//v8/src/objects/field-type.cc",
    "//v8/src/objects/js-array-buffer.cc",
    "//v8/src/objects/js-atomics-synchronization.cc",
    "//v8/src/objects/js-function.cc",
    "//v8/src/objects/js-objects.cc",
    "//v8/src/objects/js-raw-json.cc",
    "//v8/src/objects/js-regexp.cc",
    "//v8/src/objects/js-temporal-objects.cc",
    "//v8/src/objects/keys.cc",
    "//v8/src/objects/literal-objects.cc",
    "//v8/src/objects/lookup.cc",
    "//v8/src/objects/lookup-cache.cc",
    "//v8/src/objects/managed.cc",
    "//v8/src/objects/map.cc",
    "//v8/src/objects/map-updater.cc",
    "//v8/src/objects/module.cc",
    "//v8/src/objects/objects.cc",
    "//v8/src/objects/object-type.cc",
    "//v8/src/objects/option-utils.cc",
    "//v8/src/objects/ordered-hash-table.cc",
    "//v8/src/objects/property.cc",
    "//v8/src/objects/property-descriptor.cc",
    "//v8/src/objects/scope-info.cc",
    "//v8/src/objects/shared-function-info.cc",
    "//v8/src/objects/simd.cc",
    "//v8/src/objects/source-text-module.cc",
    "//v8/src/objects/string.cc",
    "//v8/src/objects/string-comparator.cc",
    "//v8/src/objects/string-forwarding-table.cc",
    "//v8/src/objects/string-table.cc",
    "//v8/src/objects/swiss-name-dictionary.cc",
    "//v8/src/objects/symbol-table.cc",
    "//v8/src/objects/synthetic-module.cc",
    "//v8/src/objects/tagged-impl.cc",
    "//v8/src/objects/template-objects.cc",
    "//v8/src/objects/templates.cc",
    "//v8/src/objects/transitions.cc",
    "//v8/src/objects/type-hints.cc",
    "//v8/src/objects/value-serializer.cc",
    "//v8/src/parsing/token.cc",
    "//v8/src/parsing/func-name-inferrer.cc",
    "//v8/src/parsing/import-assertions.cc",
    "//v8/src/parsing/literal-buffer.cc",
    "//v8/src/parsing/parse-info.cc",
    "//v8/src/parsing/parser.cc",
    "//v8/src/parsing/parsing.cc",
    "//v8/src/parsing/pending-compilation-error-handler.cc",
    "//v8/src/parsing/preparse-data.cc",
    "//v8/src/parsing/preparser.cc",
    "//v8/src/parsing/rewriter.cc",
    "//v8/src/parsing/scanner.cc",
    "//v8/src/parsing/scanner-character-streams.cc",
    "//v8/src/profiler/weak-code-registry.cc",
    "//v8/src/profiler/allocation-tracker.cc",
    "//v8/src/profiler/cpu-profiler.cc",
    "//v8/src/profiler/heap-profiler.cc",
    "//v8/src/profiler/heap-snapshot-generator.cc",
    "//v8/src/profiler/profile-generator.cc",
    "//v8/src/profiler/profiler-listener.cc",
    "//v8/src/profiler/profiler-stats.cc",
    "//v8/src/profiler/sampling-heap-profiler.cc",
    "//v8/src/profiler/strings-storage.cc",
    "//v8/src/profiler/symbolizer.cc",
    "//v8/src/profiler/tick-sample.cc",
    "//v8/src/profiler/tracing-cpu-profiler.cc",
    "//v8/src/regexp/x64/regexp-macro-assembler-x64.cc",
    "//v8/src/regexp/arm64/regexp-macro-assembler-arm64.cc",
    "//v8/src/regexp/arm/regexp-macro-assembler-arm.cc", 
    "//v8/src/regexp/regexp-utils.cc",
    "//v8/src/regexp/regexp.cc",
    "//v8/src/regexp/regexp-ast.cc",
    "//v8/src/regexp/regexp-bytecode-generator.cc",
    "//v8/src/regexp/regexp-bytecode-peephole.cc",
    "//v8/src/regexp/regexp-bytecodes.cc",
    "//v8/src/regexp/regexp-compiler.cc",
    "//v8/src/regexp/regexp-compiler-tonode.cc",
    "//v8/src/regexp/regexp-dotprinter.cc",
    "//v8/src/regexp/regexp-error.cc",
    "//v8/src/regexp/regexp-interpreter.cc",
    "//v8/src/regexp/regexp-macro-assembler.cc",
    "//v8/src/regexp/regexp-macro-assembler-tracer.cc",
    "//v8/src/regexp/regexp-parser.cc",
    "//v8/src/regexp/regexp-stack.cc",
    "//v8/src/roots/roots.cc",
    "//v8/src/runtime/runtime-weak-refs.cc",
    "//v8/src/runtime/runtime.cc",
    "//v8/src/runtime/runtime-array.cc",
    "//v8/src/runtime/runtime-atomics.cc",
    "//v8/src/runtime/runtime-bigint.cc",
    "//v8/src/runtime/runtime-classes.cc",
    "//v8/src/runtime/runtime-collections.cc",
    "//v8/src/runtime/runtime-compiler.cc",
    "//v8/src/runtime/runtime-date.cc",
    "//v8/src/runtime/runtime-debug.cc",
    "//v8/src/runtime/runtime-forin.cc",
    "//v8/src/runtime/runtime-function.cc",
    "//v8/src/runtime/runtime-futex.cc",
    "//v8/src/runtime/runtime-generator.cc",
    "//v8/src/runtime/runtime-internal.cc",
    "//v8/src/runtime/runtime-literals.cc",
    "//v8/src/runtime/runtime-module.cc",
    "//v8/src/runtime/runtime-numbers.cc",
    "//v8/src/runtime/runtime-object.cc",
    "//v8/src/runtime/runtime-operators.cc",
    "//v8/src/runtime/runtime-promise.cc",
    "//v8/src/runtime/runtime-proxy.cc",
    "//v8/src/runtime/runtime-regexp.cc",
    "//v8/src/runtime/runtime-scopes.cc",
    "//v8/src/runtime/runtime-shadow-realm.cc",
    "//v8/src/runtime/runtime-strings.cc",
    "//v8/src/runtime/runtime-symbol.cc",
    "//v8/src/runtime/runtime-temporal.cc",
    "//v8/src/runtime/runtime-test.cc",
    "//v8/src/runtime/runtime-test-wasm.cc",
    "//v8/src/runtime/runtime-trace.cc",
    "//v8/src/runtime/runtime-typedarray.cc",
    "//v8/src/runtime/runtime-wasm.cc",
    "//v8/src/sandbox/sandbox.cc",
    "//v8/src/sandbox/external-pointer-table.cc",
    "//v8/src/snapshot/embedded/embedded-empty.cc",
    "//v8/src/snapshot/embedded/embedded-file-writer.cc",
    "//v8/src/snapshot/embedded/platform-embedded-file-writer-base.cc",
    "//v8/src/snapshot/embedded/platform-embedded-file-writer-generic.cc",
    "//v8/src/snapshot/embedded/embedded-data.cc",
    "//v8/src/snapshot/code-serializer.cc",
    "//v8/src/snapshot/context-deserializer.cc",
    "//v8/src/snapshot/context-serializer.cc",
    "//v8/src/snapshot/deserializer.cc",
    "//v8/src/snapshot/object-deserializer.cc",
    "//v8/src/snapshot/read-only-deserializer.cc",
    "//v8/src/snapshot/read-only-serializer.cc",
    "//v8/src/snapshot/roots-serializer.cc",
    "//v8/src/snapshot/serializer.cc",
    "//v8/src/snapshot/serializer-deserializer.cc",
    "//v8/src/snapshot/shared-heap-deserializer.cc",
    "//v8/src/snapshot/shared-heap-serializer.cc",
    "//v8/src/snapshot/snapshot.cc",
    "//v8/src/snapshot/snapshot-compression.cc",
    "//v8/src/snapshot/snapshot-data.cc",
    "//v8/src/snapshot/snapshot-source-sink.cc",
    "//v8/src/snapshot/snapshot-utils.cc",
    "//v8/src/snapshot/startup-deserializer.cc",
    "//v8/src/snapshot/startup-serializer.cc",
    "//v8/src/strings/string-case.cc",
    "//v8/src/strings/string-stream.cc",
    "//v8/src/strings/unicode.cc",
    "//v8/src/strings/unicode-decoder.cc",
    "//v8/src/strings/uri.cc",
    "//v8/src/strings/string-builder.cc",
    "//v8/src/tasks/task-utils.cc",
    "//v8/src/tasks/cancelable-task.cc",
    "//v8/src/tasks/operations-barrier.cc",
    "//v8/src/temporal/temporal-parser.cc",
    "//v8/src/third_party/siphash/halfsiphash.cc",
    "//v8/src/torque/cc-generator.cc",
    "//v8/src/torque/cfg.cc",
    "//v8/src/torque/class-debug-reader-generator.cc",
    "//v8/src/torque/cpp-builder.cc",
    "//v8/src/torque/csa-generator.cc",
    "//v8/src/torque/declarable.cc",
    "//v8/src/torque/declarations.cc",
    "//v8/src/torque/declaration-visitor.cc",
    "//v8/src/torque/earley-parser.cc",
    "//v8/src/torque/global-context.cc",
    "//v8/src/torque/implementation-visitor.cc",
    "//v8/src/torque/instance-type-generator.cc",
    "//v8/src/torque/instructions.cc",
    "//v8/src/torque/kythe-data.cc",
    "//v8/src/torque/server-data.cc",
    "//v8/src/torque/source-positions.cc",
    "//v8/src/torque/torque-code-generator.cc",
    "//v8/src/torque/torque-compiler.cc",
    "//v8/src/torque/torque-parser.cc",
    "//v8/src/torque/type-inference.cc",
    "//v8/src/torque/type-oracle.cc",
    "//v8/src/torque/types-torque.cc",
    "//v8/src/torque/type-visitor.cc",
    "//v8/src/torque/ls/torque-language-server.cc",
    "//v8/src/torque/ls/json.cc",
    "//v8/src/torque/ls/message-handler.cc",
    "//v8/src/tracing/trace-categories.cc",
    "//v8/src/tracing/traced-value.cc",
    "//v8/src/tracing/trace-event.cc",
    "//v8/src/tracing/tracing-category-observer.cc",
    "//v8/src/trap-handler/handler-outside.cc",
    "//v8/src/trap-handler/handler-outside-posix.cc",
    "//v8/src/trap-handler/handler-shared.cc",
    "//v8/src/trap-handler/handler-inside.cc",
    "//v8/src/trap-handler/handler-inside-posix.cc",
    "//v8/src/utils/sha-256.cc",
    "//v8/src/utils/utils-v8.cc",
    "//v8/src/utils/v8dll-main.cc",
    "//v8/src/utils/version.cc",
    "//v8/src/utils/address-map.cc",
    "//v8/src/utils/bit-vector.cc",
    "//v8/src/utils/detachable-vector.cc",
    "//v8/src/utils/hex-format.cc",
    "//v8/src/utils/identity-map.cc",
    "//v8/src/utils/memcopy.cc",
    "//v8/src/utils/ostreams.cc",
    "//v8/src/wasm/baseline/liftoff-assembler.cc",
    "//v8/src/wasm/baseline/liftoff-compiler.cc",
    "//v8/src/wasm/assembler-buffer-cache.cc",
    "//v8/src/wasm/canonical-types.cc",
    "//v8/src/wasm/c-api.cc",
    "//v8/src/wasm/code-space-access.cc",
    "//v8/src/wasm/constant-expression.cc",
    "//v8/src/wasm/constant-expression-interface.cc",
    "//v8/src/wasm/function-body-decoder.cc",
    "//v8/src/wasm/function-compiler.cc",
    "//v8/src/wasm/graph-builder-interface.cc",
    "//v8/src/wasm/jump-table-assembler.cc",
    "//v8/src/wasm/local-decl-encoder.cc",
    "//v8/src/wasm/memory-tracing.cc",
    "//v8/src/wasm/module-compiler.cc",
    "//v8/src/wasm/module-decoder.cc",
    "//v8/src/wasm/module-instantiate.cc",
    "//v8/src/wasm/names-provider.cc",
    "//v8/src/wasm/pgo.cc",
    "//v8/src/wasm/simd-shuffle.cc",
    "//v8/src/wasm/stacks.cc",
    "//v8/src/wasm/streaming-decoder.cc",
    "//v8/src/wasm/sync-streaming-decoder.cc",
    "//v8/src/wasm/value-type.cc",
    "//v8/src/wasm/wasm-code-manager.cc",
    "//v8/src/wasm/wasm-debug.cc",
    "//v8/src/wasm/wasm-disassembler.cc",
    "//v8/src/wasm/wasm-engine.cc",
    "//v8/src/wasm/wasm-external-refs.cc",
    "//v8/src/wasm/wasm-features.cc",
    "//v8/src/wasm/wasm-import-wrapper-cache.cc",
    "//v8/src/wasm/wasm-init-expr.cc",
    "//v8/src/wasm/wasm-js.cc",
    "//v8/src/wasm/wasm-module.cc",
    "//v8/src/wasm/wasm-module-builder.cc",
    "//v8/src/wasm/wasm-module-sourcemap.cc",
    "//v8/src/wasm/wasm-objects.cc",
    "//v8/src/wasm/wasm-opcodes.cc",
    "//v8/src/wasm/wasm-result.cc",
    "//v8/src/wasm/wasm-serialization.cc",
    "//v8/src/wasm/wasm-subtyping.cc",
    "//v8/src/zone/accounting-allocator.cc",
    "//v8/src/zone/type-stats.cc",
    "//v8/src/zone/zone.cc",
    "//v8/src/zone/zone-segment.cc",
    "//v8/src/utils/allocation_utils.cc",
    "//v8/src/torque/ls/json-parser-torque-ls.cc",
    "//v8/src/torque/utils-torque.cc",
    "//v8/src/regexp/experimental/experimental.cc",
    "//v8/src/regexp/experimental/experimental-bytecode.cc",
    "//v8/src/regexp/experimental/experimental-compiler.cc",
    "//v8/src/regexp/experimental/experimental-interpreter.cc",
    "//v8/src/handles/global-handles.cc",
    "//v8/src/handles/handles.cc",
    "//v8/src/handles/local-handles.cc",
    "//v8/src/handles/persistent-handles.cc",
    "//v8/src/handles/shared-object-conveyor-handles.cc",
    "//v8/src/snapshot/snapshot-external.cc",
    "//v8/src/objects/intl-objects.cc",
    "//v8/src/runtime/runtime-intl.cc",
    "//v8/src/objects/js-date-time-format.cc",
    "//v8/src/objects/js-display-names.cc",
    "//v8/src/objects/js-duration-format.cc",
    "//v8/src/objects/js-list-format.cc",
    "//v8/src/objects/js-number-format.cc",
    "//v8/src/objects/js-locale.cc",
    "//v8/src/objects/js-plural-rules.cc",
    "//v8/src/objects/js-relative-time-format.cc",
    "//v8/src/objects/js-segmenter.cc",
    "//v8/src/objects/js-segment-iterator.cc",
    "//v8/src/objects/js-segments.cc",
    "//v8/src/objects/js-collator.cc",
    "//v8/src/objects/js-break-iterator.cc",
    "//v8/src/strings/char-predicates.cc",
    "//v8/src/ic/accessor-assembler.cc",
    "//v8/src/ic/binary-op-assembler.cc",
    "//v8/src/ic/call-optimization.cc",
    "//v8/src/ic/handler-configuration.cc",
    "//v8/src/ic/ic-stats.cc",
    "//v8/src/ic/ic.cc",
    "//v8/src/ic/keyed-store-generic.cc",
    "//v8/src/ic/stub-cache.cc",
    "//v8/src/ic/unary-op-assembler.cc",
    "//v8/src/init/bootstrapper.cc",
    "//v8/src/init/icu_util.cc",
    "//v8/src/init/isolate-allocator.cc",
    "//v8/src/init/setup-isolate-deserialize.cc",
    "//v8/src/init/setup-isolate-full.cc",
    "//v8/src/init/startup-data-util.cc",
    "//v8/src/init/v8.cc",
    "//v8/src/inspector/custom-preview.cc",
    "//v8/src/inspector/injected-script.cc",
    "//v8/src/inspector/inspected-context.cc",
    "//v8/src/inspector/remote-object-id.cc",
    "//v8/src/inspector/search-util.cc",
    "//v8/src/inspector/string-16.cc",
    "//v8/src/inspector/string-util.cc",
    "//v8/src/inspector/test-interface.cc",
    "//v8/src/inspector/v8-console-agent-impl.cc",
    "//v8/src/inspector/v8-console-message.cc",
    "//v8/src/inspector/v8-console.cc",
    "//v8/src/inspector/v8-debugger-agent-impl.cc",
    "//v8/src/inspector/v8-debugger-id.cc",
    "//v8/src/inspector/v8-debugger-script.cc",
    "//v8/src/inspector/v8-debugger.cc",
    "//v8/src/inspector/v8-heap-profiler-agent-impl.cc",
    "//v8/src/inspector/v8-inspector-impl.cc",
    "//v8/src/inspector/v8-inspector-session-impl.cc",
    "//v8/src/inspector/v8-profiler-agent-impl.cc",
    "//v8/src/inspector/v8-regex.cc",
    "//v8/src/inspector/v8-runtime-agent-impl.cc",
    "//v8/src/inspector/v8-schema-agent-impl.cc",
    "//v8/src/inspector/v8-stack-trace-impl.cc",
    "//v8/src/inspector/v8-string-conversions.cc",
    "//v8/src/inspector/v8-value-utils.cc",
    "//v8/src/inspector/v8-webdriver-serializer.cc",
    "//v8/src/inspector/value-mirror.cc",
    "//v8/src/interpreter/bytecode-array-builder.cc",
    "//v8/src/interpreter/bytecode-array-iterator.cc",
    "//v8/src/interpreter/bytecode-array-random-iterator.cc",
    "//v8/src/interpreter/bytecode-array-writer.cc",
    "//v8/src/interpreter/bytecode-decoder.cc",
    "//v8/src/interpreter/bytecode-flags.cc",
    "//v8/src/interpreter/bytecode-generator.cc",
    "//v8/src/interpreter/bytecode-label.cc",
    "//v8/src/interpreter/bytecode-node.cc",
    "//v8/src/interpreter/bytecode-operands.cc",
    "//v8/src/interpreter/bytecode-register-optimizer.cc",
    "//v8/src/interpreter/bytecode-register.cc",
    "//v8/src/interpreter/bytecode-source-info.cc",
    "//v8/src/interpreter/bytecodes.cc",
    "//v8/src/interpreter/constant-array-builder.cc",
    "//v8/src/interpreter/control-flow-builders.cc",
    "//v8/src/interpreter/handler-table-builder.cc",
    "//v8/src/interpreter/interpreter-assembler.cc",
    "//v8/src/interpreter/interpreter-generator.cc",
    "//v8/src/interpreter/interpreter-intrinsics-generator.cc",
    "//v8/src/interpreter/interpreter-intrinsics.cc",
    "//v8/src/interpreter/interpreter.cc",
    "//v8/src/json/json-parser.cc",
    "//v8/src/json/json-stringifier.cc",
    "//v8/src/libplatform/default-foreground-task-runner.cc",
    "//v8/src/libplatform/default-job.cc",
    "//v8/src/libplatform/default-platform.cc",
    "//v8/src/libplatform/default-worker-threads-task-runner.cc",
    "//v8/src/libplatform/delayed-task-queue.cc",
    "//v8/src/libplatform/task-queue.cc",
    "//v8/src/libplatform/worker-thread.cc",
    "//v8/src/libplatform/tracing/trace-buffer.cc",
    "//v8/src/libplatform/tracing/trace-config.cc",
    "//v8/src/libplatform/tracing/trace-event-listener.cc",
    "//v8/src/libplatform/tracing/trace-object.cc",
    "//v8/src/libplatform/tracing/trace-writer.cc",
    "//v8/src/libplatform/tracing/tracing-controller.cc",
    "//v8/src/libsampler/sampler.cc",
    "//v8/src/logging/counters.cc",
    "//v8/src/logging/local-logger.cc",
    "//v8/src/logging/log-file.cc",
    "//v8/src/logging/log.cc",
    "//v8/src/logging/metrics.cc",
    "//v8/src/logging/runtime-call-stats.cc",
    "//v8/src/logging/tracing-flags.cc",
    "//v8/src/libplatform/default-platform-wrap.cc",

  ]


}


