// Copyright 2020 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BASE_TRACE_EVENT_TRACE_EVENT_EMPTY_H_
#define BASE_TRACE_EVENT_TRACE_EVENT_EMPTY_H_

#define PERFETTO_INTERNAL_ADD_EMPTY_EVENT()

#define INTERNAL_TRACE_EVENT_ADD(...)
#define INTERNAL_TRACE_EVENT_ADD_SCOPED(...)
#define INTERNAL_TRACE_EVENT_ADD_WITH_ID(...)
#define INTERNAL_TRACE_LOG_MESSAGE(...)
#define INTERNAL_TRACE_EVENT_ADD_SCOPED_WITH_FLOW(...)
#define INTERNAL_TRACE_EVENT_ADD_WITH_ID_TID_AND_TIMESTAMP(...)
#define INTERNAL_TRACE_EVENT_ADD_WITH_ID_TID_AND_TIMESTAMPS(...)
#define TRACE_HEAP_PROFILER_API_SCOPED_TASK_EXECUTION

#define INTERNAL_TRACE_EVENT_GET_CATEGORY_INFO(category_group)
#define INTERNAL_TRACE_EVENT_CATEGORY_GROUP_ENABLED_FOR_RECORDING_MODE() false

#define TRACE_EVENT_MARK_WITH_TIMESTAMP1(category_group, name, timestamp, arg1_name, arg1_val)

#define INTERNAL_TRACE_EVENT_ADD_WITH_TIMESTAMP(...)

#endif